---
- hosts: app
  tasks:
   - name: Enable Apache rewrite module.
     apache2_module: name=wsgi state=present
     notify: restart apache

  handlers:
   - name: restart apache
     service: name=apache2 state=restarted
