--- # This is to install HTTPD server on app servers
- hosts: local
  remote_user: root
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  vars:
    username: venky
  tasks:
  - name: Install httpd server
    yum:
      name=httpd
      state=present
    notify: 
    - startservice

  - name: create if index file does not exists
    file:
      path: /var/www/html/index.html
      state: touch

  - name: add line if does not exists
    lineinfile:
      path: /var/www/html/index.html
      regexp: ^Hostname=
      line: Hostname={{ansible_hostname}}

  handlers:
  - name: startservice
    service:
      name=httpd
      state=restarted
